import AuthGard from "@/components/AuthGard";
import Dashboard from "@/components/Dashboard/Dashboard";
import MainLayout from "@/components/common/header/MainLayout";
import Login from "@/components/login/Login";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const navigate = (name: any) => {
    router.push("/login");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthGard />
    </>
  );
}
